version: "3"

services:
  app:
    image: maksru/bookstore:hw_2
    links:
      - database-server:database
    environment:
      - spring.datasource.url=jdbc:postgresql://medmap-db:5432/bookstore
      - spring.datasource.username=postgres
      - spring.datasource.password=admin
    depends_on:
      - database-server
    ports:
      - 8082:8082

  database-server:
    container_name: medmap-db
    hostname: medmap-db
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=admin
      - POSTGRES_DB=bookstore
    image: maksru/bookstore:hw_db_2
    ports:
      - 5432:5432
    volumes:
       - ./sql:/docker-entrypoint-initdb.d
